### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ashishTheDev07**

### CODE REVIEW

**Review by inaseem — CHANGES_REQUESTED** [review]
Please Change The `.txt` Extension To `.java`

**Comment by ashishTheDev07** [comment]
Can you create a separate folder for Logical coding ?

**Comment by inaseem** [comment]
> Can you create a separate folder for Logical coding ?

Sure.

**Comment by inaseem** [comment]
Hi, @Ashish221293 `CodeSnippets` Directory is now available. You can add your code into that directory.

**Pull request closed without merging**
